---
title: Indivisible Farmington Valley
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: representatives
  values:
    main-image: 
    phone-numbers: 
    website: 
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image: 
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
subtitle: We are Connecticut citizens resisting the Trump agenda through civic action.
email: 
baseurl: 
url: 
twitter_username: 
github_username: 
facebook_username: 
background-image: "/uploads/Title%20Photo.jpg"
mailchimp-form-embed: 
member-count: 
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: 
