---
title: Indivisible Farmington Valley, CT
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
    permalink: "/successes/path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    main-image: 
    phone-numbers: 
    website: 
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image: 
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
subtitle: 'Indivisible Farmington Valley '
email: indivisiblefv.membership@gmail.com
baseurl: 
url: 
twitter_username: 
github_username: 
facebook_username: IndivisibleFarmingtonValley
background-image: "/uploads/Title%20Photo-26314e.jpg"
mailchimp-form-embed: "<!-- Begin MailChimp Signup Form -->\n<link href=\"//cdn-images.mailchimp.com/embedcode/classic-10_7.css\"
  rel=\"stylesheet\" type=\"text/css\">\n<style type=\"text/css\">\n\t#mc_embed_signup{background:#fff;
  clear:left; font:14px Helvetica,Arial,sans-serif; }\n\t/* Add your own MailChimp
  form style overrides in your site stylesheet or in this style block.\n\t   We recommend
  moving this block and the preceding CSS link to the HEAD of your HTML file. */\n</style>\n<div
  id=\"mc_embed_signup\">\n<form action=\"//Indivisiblefv.us15.list-manage.com/subscribe/post?u=9940e0682286cd25d46e90dde&amp;id=564f116614\"
  method=\"post\" id=\"mc-embedded-subscribe-form\" name=\"mc-embedded-subscribe-form\"
  class=\"validate\" target=\"_blank\" novalidate>\n    <div id=\"mc_embed_signup_scroll\">\n\t<h2>Become
  a Member</h2>\n<div class=\"indicates-required\"><span class=\"asterisk\">*</span>
  indicates required</div>\n<div class=\"mc-field-group\">\n\t<label for=\"mce-EMAIL\">Email
  Address  <span class=\"asterisk\">*</span>\n</label>\n\t<input type=\"email\" value=\"\"
  name=\"EMAIL\" class=\"required email\" id=\"mce-EMAIL\">\n</div>\n<div class=\"mc-field-group\">\n\t<label
  for=\"mce-FNAME\">First Name </label>\n\t<input type=\"text\" value=\"\" name=\"FNAME\"
  class=\"\" id=\"mce-FNAME\">\n</div>\n<div class=\"mc-field-group\">\n\t<label for=\"mce-LNAME\">Last
  Name </label>\n\t<input type=\"text\" value=\"\" name=\"LNAME\" class=\"\" id=\"mce-LNAME\">\n</div>\n\t<div
  id=\"mce-responses\" class=\"clear\">\n\t\t<div class=\"response\" id=\"mce-error-response\"
  style=\"display:none\"></div>\n\t\t<div class=\"response\" id=\"mce-success-response\"
  style=\"display:none\"></div>\n\t</div>    <!-- real people should not fill this
  in and expect good things - do not remove this or risk form bot signups-->\n    <div
  style=\"position: absolute; left: -5000px;\" aria-hidden=\"true\"><input type=\"text\"
  name=\"b_9940e0682286cd25d46e90dde_564f116614\" tabindex=\"-1\" value=\"\"></div>\n
  \   <div class=\"clear\"><input type=\"submit\" value=\"Subscribe\" name=\"subscribe\"
  id=\"mc-embedded-subscribe\" class=\"button\"></div>\n    </div>\n</form>\n</div>\n<script
  type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script
  type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes
  = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var
  $mcj = jQuery.noConflict(true);</script>\n<!--End mc_embed_signup-->\n"
member-count: 
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: 
